-- Clear and insert all unique vendors from CSV files
-- Total unique vendors: 754

-- Create table if not exists
CREATE TABLE IF NOT EXISTS vendors (
  id SERIAL PRIMARY KEY,
  vendor_number TEXT NOT NULL UNIQUE,
  vendor_name TEXT NOT NULL,
  is_active BOOLEAN DEFAULT true,
  created_at TIMESTAMP DEFAULT NOW(),
  updated_at TIMESTAMP DEFAULT NOW()
);

-- Clear existing vendors (optional - comment out to keep existing)
-- TRUNCATE TABLE vendors CASCADE;


-- Chunk 1 of 8
INSERT INTO vendors (vendor_number, vendor_name, is_active)
VALUES 
('1-800-Radiator', '1-800-Radiator & A/C / See Forever LLC', true),
('1Source', '1 Source Transporation', true),
('200', '200 AND WEST HOLDINGS', true),
('360 Towing', '360 Towing & Recovery', true),
('401K', '401 K', true),
('57Service', '57 Service & Storage LLC', true),
('61Tire', '61 Tire Co. Inc.', true),
('700', '700 Credit LLC    / Open Dealer Exchange', true),
('901 Sounds', '901 Sounds Auto Accessories', true),
('A to Z', 'A to Z Printing & Signs Corp.', true),
('A&B', 'A & B Body Shop, Inc.', true),
('A&H', 'A & H Ironworks Ptnsp', true),
('A1 Auto', 'A1 Auto Enterprise', true),
('A-1Fire', 'A-1 Fire Protection', true),
('A-1Sales', 'A-1 Sales & Wrecker / Charles D. Taylor', true),
('AAhmed', 'Akeem Ahmed', true),
('AAP', 'AAP of Collierville # 4144', true),
('ABCoA', 'Advanced Business Computers of America', true),
('Able', 'Able Agency Inc.', true),
('AccuTrade', 'Accu-Trade LLC', true),
('Acee', 'Acee Company', true),
('Acura', 'Acura of Memphis', true),
('ADAS', 'ADAS Solutions USA Inc.', true),
('ADATL', 'ADESA  - ATLANTA', true),
('ADBirmingham', 'Adesa Birmingham', true),
('AdCincinnati', 'Adesa Cincinnati/Dayton', true),
('ADDAL', 'ADESA DALLAS', true),
('Addison', 'Addison Glass', true),
('ADESA', 'ADESA MEMPHIS', true),
('Adesa Charlotte', 'Adesa Charlotte', true),
('Adesa Chicago', 'Adesa Chicago', true),
('Adesa Phoenix', 'Adesa Phoenix', true),
('Adesa Stlouis', 'Adesa St. Louis', true),
('AdesaJax', 'Adesa Jacksonville', true),
('ADIn', 'Adesa Indianapolis', true),
('ADLexington', 'Adesa Lexington', true),
('ADLittleRock', 'Adesa Little Rock', true),
('ADNASH', 'ADESA NASH', true),
('AdOffsite', 'Adesa Offsite Wholesale', true),
('ADOrlando', 'Adesa Orlando', true),
('ADP', 'ADP Invoices', true),
('AdTulsa', 'Adesa Tulsa', true),
('AdvanceAuto', 'General Parts, Inc. / Carquest / Advance Auto', true),
('Advantage', 'Advantage Auto Service', true),
('AELog', 'AE Logistics LLC', true),
('AEX', 'AUTO EXCHANGE', true),
('AFCO', 'AFCO Direct', true),
('Ajax', 'Ajax Partners LLC', true),
('AjaxFloorPlan', 'Ajax Partners LLC', true),
('Alcorn', 'Alcorn County Justice Court', true),
('Alias', 'Alias Subpoena, LLC', true),
('All Recovery', 'All Star Recovery LLC', true),
('All South', 'All South Equipment Inc.', true),
('Allangles', 'All Angles Transportation LLC', true),
('AllDay', 'Kamiran Said Hussien  /   All Day Towing', true),
('AllFamily', 'All Family Finance LLC', true),
('Allsouth', 'All South Equipment Sales, Inc', true),
('ALLSTA', 'ALL STAR WHOLESALE', true),
('AllStar', 'All Star Auto Group .', true),
('Ally', 'Ally / Smart Auction', true),
('AlmonEllis', 'Almon M. Ellis, Attorney at Law', true),
('Amazon', 'Amazon', true),
('Ambetter', 'Ambetter Health Insurance', true),
('AmerAtlanta', 'America`s AA Atlanta', true),
('Americ`s', 'America`s AA Birmingham', true),
('American', 'American Car Center', true),
('American Recovery', 'American Recovery Service', true),
('AmericanDent', 'American Dent Company / William Conner Fleming', true),
('Amex', 'American Express - NEW', true),
('AmExpress', 'American Express - OLD', true),
('ANAAAtlanta', 'Auto Nation Auto Auction Atlanta', true),
('ANAutoAuction', 'Auto Nation Auto Auction of Orlando', true),
('ANFord', 'Auto Nation Ford', true),
('ANGMC', 'Auto Nation GMC', true),
('ANHonda', 'Auto Nation Honda', true),
('ANNissan', 'Auto Nation Nissan', true),
('April', 'April Rosenbaum', true),
('Arnold', 'Arnold Yanes', true),
('ASAP', 'A.S.A.P. Towing of Central VA', true),
('ASTART', 'AUTO START', true),
('Astro', 'Astro Auto Glass', true),
('AT&T', 'AT&T', true),
('ATC', 'ATC Group Services, LLC', true),
('ATD', 'ATD Logistics LLC', true),
('Atlantic', 'Atlantic Auto Sales LLC', true),
('Atlas', 'Atlas Recovery Systems LLC', true),
('Atmos', 'Atmos Energy', true),
('Auction', 'Auction Access', true),
('AUTO M', 'AUTO MAX OF MEMPHIS', true),
('AutoBeauty', 'Auto Beauty Center of KC, LLC', true),
('AutoFasteners', 'Automotive Fasteners of Memphis', true),
('Autogate', 'Autogate of Nashville', true),
('AutoMaster', 'Auto Master System', true),
('AutoPaint', 'Auto Paint Specialists Nashville', true),
('AUTOWM', 'AUTO MAX - WEST MEMPHIS', true),
('AutoXChange', 'Auto X Change', true),
('Autozone', 'Auto Zone', true),
('Ayanna', 'Ayanna M. Ajanaku', true),
('B & C Towing', 'B & C Towing and Recovery', true),
('B & L', 'B & L Cargo LLC', true)
ON CONFLICT (vendor_number) DO UPDATE SET
  vendor_name = EXCLUDED.vendor_name,
  updated_at = NOW();

-- Chunk 2 of 8
INSERT INTO vendors (vendor_number, vendor_name, is_active)
VALUES 
('B&B', 'B&B Transportation', true),
('Backlot', 'Backlot Cars Inc.', true),
('BankDirect', 'Bank Direct Capital', true),
('Barkley', 'Locke D. Barkley', true),
('Barretts', 'Barrett`s Towing and Recovery', true),
('Baylis Earle Farrell', 'Bayliss Earle Farrell III', true),
('BCBS', 'Blue Cross Blue Shield TN', true),
('Becky', 'Rebecca Hadden', true),
('Bell', 'Bell Motor Express Inc.', true),
('BentonJustice', 'Benton County Justice Court', true),
('BestOffice', 'Best Office Staff', true),
('BHC', 'BHC Automotive', true),
('BigSnatch', 'John Kimbrell / Big Snatch Recovery', true),
('BISH', 'KEITH BISHOP', true),
('BISHOP', 'BISHIP', true),
('BizPrint', 'Biz Print Solutions Mark Harrison', true),
('BKeen', 'Bill Keen Trucking Inc', true),
('Blackline', 'Blackline Auto & Performance LLC', true),
('Blaylock/Brown', 'Blaylock/Brown Construction', true),
('BLUFF', 'BLUFF CITY', true),
('BobbyDepriest', 'Bobby Depriest', true),
('Bobo', 'Bobo Services LLC    /  William Skinner', true),
('Bolivar', 'Bolivar County Justice Court', true),
('Bookitout', 'Bookitout, Inc.', true),
('Bowers', 'Bowers Logistics', true),
('Brantley', 'Brantley and Brantley Adjusters Inc', true),
('Brothers', 'Brothers and Sons', true),
('Bursi', 'F. Michael Bursi', true),
('Byrd`s', 'Byrd`s Automotive Inc.', true),
('C&M', 'C&M Coaching   c/o A Plus Accounting', true),
('Cains', 'Cains Auto Transport', true),
('CAL', 'CAL SMITH', true),
('Calhoun', 'Calhoun County Justice Court', true),
('Cannon', 'Cannon Chevy Buick GMC Cadillax', true),
('Car Guys', 'Car Guys Auto Recon LLC', true),
('CarChoice', 'Car Choice', true),
('CarFinancial', 'Car Financial Services Inc', true),
('Carmart', 'Car Mart', true),
('CarmaxChicago', 'Car Max Chicago', true),
('CarMaxDayton', 'Car Max Dayton', true),
('CarMaxDesMoines', 'Car Max Des Moines', true),
('CarMaxGermantown', 'Car Max Germantown', true),
('CarMaxLogistics', 'Car Max Logistics', true),
('CarMaxLouisville', 'Car Max Louisville', true),
('CarMaxMurfressboro', 'Car Max Murfreesboro', true),
('CarMaxNashville', 'Car Max Nashville', true),
('CarMaxNewnan', 'Car Max Newnan', true),
('CarMaxransport', 'Car Max Transport', true),
('CarMaxSouthwest', 'Car Max Southwest Freeway', true),
('CarMaxStLouis', 'Car Max St Louis', true),
('Carolina', 'Carolina Transportation Inc', true),
('Carpenter', 'Deborah Carpenter', true),
('Carworld', 'Car World Group, Inc.', true),
('Carz', 'Carz Sale and Lease Inc.', true),
('Castro', 'Castro Enterprises Inc', true),
('CBIC', 'CBIC Bank Account for I Finance', true),
('CBrewer', 'Chris Brewer', true),
('CentLink', 'Century Link', true),
('Certifit', 'Certifit', true),
('CES', 'CES Towing and Recovery', true),
('Chad Martin', 'Chad Martin / Martin Consulting & Mgt LLC dba MCM', true),
('Chickasaw Justic', 'Chickasaw County Justice Court', true),
('Choctow Justice', 'Choctow County Justice Court', true),
('Christys', 'Christy`s Auto Mobile Glass', true),
('ChuHuttonChevy', 'Chuck Hutton Chevy Inc', true),
('CHuttonToyota', 'Chuck Hutton Toyota', true),
('Cigna', 'Cigna', true),
('Circuit', 'Circuit Clerks Office', true),
('Cityhenrando', 'City of Hernando', true),
('CityMemImpound', 'City of Memphis Impound Lot', true),
('CityOB', 'City of Olive Branch', true),
('CJones', 'Cliff Jones', true),
('CJR', 'CJR Development Inc.', true),
('CJR Servicing', 'CJR Servicing LLC', true),
('CLA', 'Clifton Larson Allen', true),
('Clarksville', 'Clarksville Auto Auction', true),
('ClayJustice', 'Clay County Justice Court', true),
('CoahomaJustice', 'Coahoma County Justice Court', true),
('Cobb', 'Magistrate Court of Cobb County', true),
('Cobbs', 'Cobbs Cargo Carry', true),
('COLEMA', 'GOODMAN', true),
('ColemanTayWinchester', 'Coleman Taylor Winchester', true),
('ColeTayMend', 'Coleman Taylor Mendenhall', true),
('ColeTaySouth', 'Coleman Taylor Southaven', true),
('COLL', 'COLLIERVILLE AUTO CENTER', true),
('Collierville DJR', 'Collierville Dodge Jeep Ram', true),
('Collins', 'Robert Collins Jr.', true),
('COLUMB', 'Columbus Autoville', true),
('Comcast', 'Comcast', true),
('Corey', 'Corey Scruggs', true),
('CougChemical', 'Cougar Chemical', true),
('CountryFord', 'Country Ford', true),
('County Line', 'County Line Towing and Recovery', true),
('CParrish', 'Cameron Parrish', true),
('CPrice', 'Cedris Price', true),
('CRay', 'C-Ray Solutions LLC  dba Retail Ready Auto', true),
('CredCapti', 'Creditors Capitive Formation Corp', true),
('Credit', 'Credit Acceptance', true),
('CreditBureau', 'Credit Bureau Connection', true),
('CRosenbaum', 'Christopher B. Rosenbaum', true)
ON CONFLICT (vendor_number) DO UPDATE SET
  vendor_name = EXCLUDED.vendor_name,
  updated_at = NOW();

-- Chunk 3 of 8
INSERT INTO vendors (vendor_number, vendor_name, is_active)
VALUES 
('Crypton', 'Crypton Mobile', true),
('Crystal Clean', 'Crystal Clean LLC', true),
('CT Jax', 'Coleman Taylor - Jackson TN', true),
('Cyber', 'Cyber Solutions', true),
('DAA', 'Dealer`s Auto Auction of Memphis', true),
('DAAMUR', 'DEALERS MURPHREESBORO', true),
('DanielBrown', 'Daniel Brown', true),
('Darby`s', 'Darby`s Tire & Auto Service', true),
('Dave Meeker', 'Dave Meeker Auto, Inc.', true),
('Davidson', 'Davidson County Sheriff', true),
('DavisTrans', 'Samuel T. Davis  dba Davis Transport Co.', true),
('Ddetail', 'D. Detailing LLC', true),
('DeaJax', 'Dealers Auto Auction of Jackson', true),
('Dealer.com', 'Dealer.com', true),
('DealerPrep', 'Cole, Timothy K. / Dealer Prep', true),
('Debbi', 'Deborah Scruggs', true),
('Dekalb', 'Magistrate Court of Dekalb County', true),
('Delaney', 'Delaney Transport   / Landon Heath Delaney', true),
('DeltaLight', 'Delta Lighting Products. Inc.', true),
('Dent', 'Dent Remedy', true),
('Derrick Love', 'Derrick James Love / Love & Associates', true),
('DesotoJustice', 'Desoto County Justice Court', true),
('DesotoTaxColl', 'Joey Treadway Desoto County Tax Collector', true),
('DetailKIng', 'Detail King', true),
('Deuces', 'Deuces Transport LLC   / John Thomas', true),
('DHoward', 'Daron Howard', true),
('Dinkelspiel', 'Dinkelspiel Rasmussen & Mink, PLLC.', true),
('DisAutoGlass', 'Discount Auto Glass', true),
('DiscountMuffler', 'Ottis Automotive DBA Discount Muffler', true),
('Discounttire', 'Discount Tire', true),
('DisMuff NEW', 'Jamie`s Discount Muffler & Auto Repair LLC', true),
('DisMufflers', 'Discount Mufflers & Customs', true),
('Dixon', 'Dixon Recovery LLC', true),
('DJames', 'Darrell James Sr', true),
('Docusign', 'Docusign, Inc.', true),
('Dons', 'Don`s Auto Upholstrey', true),
('dorothy', 'Dorothy Marindale', true),
('DrDetail', 'Dr. Detail of Nashville LLC', true),
('DRN', 'Digitial Recogniton Network Inc', true),
('DTS', 'DTS Towing', true),
('EAN', 'EAN HOLDINGS, LLC', true),
('EAS', 'ELITE AUTO SALES', true),
('ebay', 'ebay', true),
('EBox', 'EBox', true),
('ECBI', 'E-CBI', true),
('Eddie', 'Edward J. Hafner', true),
('EHarper', 'Elizabeth Harper', true),
('Elitek', 'Elitek Vehicle Services', true),
('Ellis', 'Ellis Battery', true),
('EMC', 'EMC Insurance Companies', true),
('Enfield', 'Enfield`s Auto LLC', true),
('Ennis', 'Ennis Auto Transport LLC', true),
('Entergy', 'Entergy', true),
('EnterVech', 'Enterprise Vechile Exchange', true),
('EntFleet', 'Enterprise Fleet Management Trust', true),
('Equifax', 'Equifax Verification Services', true),
('Estrella', 'Estrella TV Memphis / Dora P. Casas', true),
('Everest Motors', 'Everest Motors Inc.', true),
('Evergreen', 'Evergreen Logistical Services LLC', true),
('Executive', 'Executive Transporting    /   Cheo Ware', true),
('ExpCreditAuto', 'Express Credit Auto', true),
('Express', 'Express Services Inc.', true),
('Express Transport', 'Sammy L. Snead Jr.', true),
('ExpressCredit', 'Express Credit Auto', true),
('EZ', 'EZ AUTO INC', true),
('Ezlivin', 'Ezlivin Express', true),
('EZTools', 'EZ Tools LLC', true),
('Farrington', 'Farrington`s Transport / Alvin Ross Farrington', true),
('FCI', 'FCI of Memphis', true),
('FIFTH', 'FIFTH THIRD', true),
('Firestone', 'Firestone Complete Auto Care', true),
('First Source', 'First Source', true),
('Five Star', 'Five Star Auto Care Inc.', true),
('Forex', 'Forex LLC', true),
('ForrestJustice', 'Forrest County Justice Court', true),
('Franks', 'Frank`s Garage', true),
('Freeland CDJR', 'Freeland CDJR', true),
('Fuelman', 'Fuelman', true),
('Fulton', 'Magistrate of Fulton County', true),
('GarnExp', 'Garnishment Express LLC', true),
('GarnPaychex', 'Garnish Payhex', true),
('Gate # 1027', 'Gateway Tire & Service # 1027', true),
('Gateway', 'Gateway Tire & Service     Dunlap & Kyle Co, Inc.', true),
('Gateway Nashville', 'Gateway Tire & Service 2002', true),
('GBurcham', 'Gary Burcham', true),
('Geico', 'Geico', true),
('GeneralSessions', 'General Sessions Civil Court   Attn: JA Clerk', true),
('Genesis', 'Genesis Motors', true),
('GenesisRX', 'Genesis RX LLC', true),
('GeneTaylor', 'Gene Taylor & Sons Plumbing Co. Inc.', true),
('Geo', 'Geo Transportation', true),
('George', 'George County Justice Court', true),
('GIG', 'GIG Logistics Inc.', true),
('GNC', 'Greg Lester / GNC Mobile Detal', true),
('GNelson', 'Gregory Nelson', true),
('Gone', 'Gone in 60 Seconds Recovery', true),
('Good', 'Good People Locksmithing LLC', true),
('Google', 'Google', true),
('Gossett', 'Gossett Motor Cars Inc.', true),
('GrayTV', 'Gray TV', true)
ON CONFLICT (vendor_number) DO UPDATE SET
  vendor_name = EXCLUDED.vendor_name,
  updated_at = NOW();

-- Chunk 4 of 8
INSERT INTO vendors (vendor_number, vendor_name, is_active)
VALUES 
('Great Chioice', 'Great Choice Investment Inc.', true),
('GregHallman', 'Greg Hallman', true),
('Grenda', 'Grenda County Justice Court', true),
('Griffith', 'Griffith Towing', true),
('Gwinnett', 'Magistrate Court of Gwinnett County', true),
('GWinston', 'Gerald K. Winston', true),
('H&H', 'H & H Delivery LLC', true),
('Happy Auto', 'Happy Auto Transport Corp', true),
('Harbor Freight', 'Harbor Freight', true),
('HarrisonJustice', 'Harrison County Justice Court', true),
('Hauling America', 'LIA Roxann Stocia dba Hauling America', true),
('Henderson', 'Henderson Recovery Inc.', true),
('HighTech', 'High Tech Locksmith', true),
('Hill', 'Hill & Associates of GA, Inc.', true),
('HindsJustCrt', 'Hinds County Justice Court', true),
('Hodge', 'Hodge Trucking', true),
('Holmes', 'Holmes County Justice Court', true),
('HomeDepot', 'Home Depot', true),
('Hometown', 'Hometown Auto & Detail    /   Timothy Heath Weaver', true),
('Hotwire', 'Hotwire Graphix / John M. Regenhardt', true),
('HPaciorko', 'Herny Paciorko', true),
('HSHyuandi', 'Homer Skelton Hyundai', true),
('Hudo', 'Hudo-dod LLC', true),
('Humana', 'Humana', true),
('Hwy70', 'Hwy 70 Car Care - Rossville', true),
('I FINA', 'I FINANCE', true),
('IAAMEM', 'INSURANCE AUTO AUCTIONS MEMPHIS', true),
('IAlcantar', 'Ileana N. Alcantar', true),
('Icon', 'Icon Collision Wholesale', true),
('IFW', 'I Finance Wholesale', true),
('Impel', 'Augmented Reality Concepts Inc.', true),
('Imperial', 'Imperial Motors & Serive LLC', true),
('IND', 'INDIVIDUAL', true),
('Infiniti', 'Infiniti of Memphis', true),
('INSPRO', 'INSURANCE PROCEEDS', true),
('Instant Credit', 'Instant Credit Auto Sales', true),
('Integrity Hot Shot', 'Integrity Hot Shot Services LLC', true),
('INTER', 'INTERSTATE CAR AND TRUCK', true),
('Intercontinental', 'Intercontinental Auto Hauler LLS', true),
('Internet Vendor', 'Internet Vendor', true),
('InvoicePaychex', 'Invoice Paychex', true),
('IPFS', 'IPFS Corporation', true),
('Irelan', 'Irelan Trucking LLC   Joseph Irelan', true),
('Itawanba', 'Itawamba County Justice Court', true),
('Ituran', 'Ituran USA Inc.', true),
('J&A', 'J & A Auto Repair', true),
('J&S', 'J & S Towing & Hauling LLC', true),
('JackieTransport', 'Jackie Transportation LLC', true),
('Jackson', 'Jackson County Justice Court', true),
('JackWalker', 'Jack D. Walker', true),
('JAllred', 'Joshua Cole Allred', true),
('James Brown', 'James Brown', true),
('Jamies', 'Jamie`s Discount Muffler & Performance', true),
('JBattaile', 'Joseph C. Battaile, CPA', true),
('JBreve', 'Jorge Breve', true),
('JerryPrather', 'Jerry Prather', true),
('JET Custom Hauling', 'JET Custom Hauling', true),
('JGilmore', 'Joseph Gilmore', true),
('Jgram', 'Jgram Transportation LLC', true),
('JGutierrez', 'Jesus A. Gutierrez', true),
('JimKerasChevy', 'Jim Keras Chevy', true),
('JimKerasSubaru', 'Jim Keras Subaru', true),
('JimKerrasNissan', 'Jim Kerras Nissan', true),
('JimmyGrayChevy', 'Jimmy Gray Chevy', true),
('JJ09', 'JJ 09 Corporation', true),
('JLT', 'JLT Auto Detail, LLC', true),
('JohnnieB', 'Johnnie B Autp', true),
('JohnTriNguyen', 'John Tri Nguyen', true),
('Jon', 'Jonathan Scruggs', true),
('JPennington', 'Justin Pennington', true),
('JR REP', 'JR REPAIR', true),
('Jramirez', 'Jesus A. Ramirez Marin', true),
('JStiles', 'James Stiles', true),
('JTwo', 'J Two Enterprise LLC', true),
('JudithKelsey', 'Judith Kelsey', true),
('Kaeser', 'Kaeser & Blair Inc.', true),
('Karn', 'Karn Automotive Products Inc', true),
('KCW', 'KCW Solutions LLC', true),
('KELLY', 'KELLY', true),
('Kennedy', 'Kennedy Auto Recovery Solutions LLC', true),
('KenSledd', 'Kenneth Sledd', true),
('Kent', 'Kent Automotive', true),
('KER', 'KERAS CAR CENTRAL', true),
('KevinDPitchford', 'Kevin D Pitchford', true),
('KevinDPritchard', 'Kevin D Pritchard', true),
('Keystone', 'Keystone', true),
('Kike', 'Kike Auto Repair Corp', true),
('Kimble', 'Kimble`s Towing', true),
('KKennedy', 'Kenya Esmeralda Kennedy', true),
('KnoxSherriff', 'Knox County Sherriff Dept', true),
('KSM', 'Katz, Sapper & Miller, LLP', true),
('Kyle', 'Kyle Sledd', true),
('LAAuto', 'L.A. Automotive', true),
('Lafayette Court', 'Lafayette County Courthouse', true),
('Lambert', 'Lambert Auto Salvage', true),
('LandersDodge', 'Landers Dodge', true),
('LandersFord', 'Landers Ford', true),
('LandersNissan', 'Landers Nissan', true),
('Landmark', 'Landmark Bank', true),
('Landrum', 'Landrum Heating & Air LLC', true)
ON CONFLICT (vendor_number) DO UPDATE SET
  vendor_name = EXCLUDED.vendor_name,
  updated_at = NOW();

-- Chunk 5 of 8
INSERT INTO vendors (vendor_number, vendor_name, is_active)
VALUES 
('Lauderdale Justice', 'Lauderdale County Justice Court', true),
('Lavish', 'Lavish Freight', true),
('Lee Justice', 'Lee County Justice Court', true),
('LefloreJustice', 'Leflore County Justice Court', true),
('Legendary', 'Legendary Auto Logistics', true),
('Lexus', 'Lexus of Memphis', true),
('LHPH', 'LHPH, LLC', true),
('Liberty', 'Liberty Recovery Services LLC', true),
('LJS', 'LJS Transport LLC', true),
('LKB', 'LKB Moving & Delivery, LLC', true),
('LKQ', 'LKQ of TN Inc.', true),
('LLF', 'LONG LEWIS FORD', true),
('LMcCarter', 'Lane McCarter', true),
('Locknroll', 'Lock-N- Roll Mobile Locksmith', true),
('Lockster02', 'Harvey, Crystal M. / Lockster', true),
('Lowe`s', 'Lowe`s', true),
('Lowndes', 'Lowndes County Justice Court', true),
('LPS', 'Loss Prevention Services, LLC', true),
('LR Recovery', 'LR Recovery and Towing LLC', true),
('LRH', 'LRH Trucking LLC', true),
('M&B', 'M & B Motors', true),
('M&M', 'M & M Recovery & Towing LLC', true),
('M&T Automotive', 'M&T Automotive', true),
('MAA', 'United Auto Exchange of Memphis', true),
('Maces', 'Mace`s Heavy Duty Towing', true),
('MadisonAuto', 'Madison Auto Car LLC', true),
('MadisonGeneral', 'Madison County General Sesssios Cout', true),
('MadisonJustice', 'Madison County Justice Court', true),
('Mads', 'Mads Auto Repairs and Service Inc', true),
('Magz', 'Magz Transport LLC  / Patrick Joseph Magagnos II', true),
('ManAtlanta', 'Manheim Atlanta', true),
('ManBirmingham', 'Manheim Birmingham', true),
('ManCentralFL', 'Manheim Central Florida', true),
('ManChicago', 'Manheim Chicago', true),
('ManCincinnati', 'Manheim Cincinnati', true),
('ManDalFW', 'Manheim Dallas-Ft Worth', true),
('MANDallas', 'MANHEIM DALLAS', true),
('ManDetriot', 'Manheim Detriot', true),
('ManFredericksburg', 'Manheim Fredericksburg', true),
('ManGeorgia', 'Manheim Georgia', true),
('ManHouston', 'Manheim  Houston', true),
('ManJax', 'Manheim Jacksonville', true),
('ManKansas City', 'Manheim Kansas City', true),
('ManLouisville', 'Manheim Louisville', true),
('ManLR', 'Manheim Little Rock', true),
('ManMilwaukee', 'Manheim Milkwaukee', true),
('ManMS', 'Manheim Mississippi', true),
('MANNASHVILLE', 'MANHEIM NASHVILLE', true),
('ManNC', 'Manheim North Carolina', true),
('ManNewOrleans', 'Manheim New Orleans', true),
('ManOhio', 'Manheim Ohio', true),
('ManOrlando', 'Manheim Orlando', true),
('ManPensacola', 'Manheim Penscaola', true),
('ManStateswville', 'Manheim Statesville', true),
('ManStLouis', 'Manheim St Louis', true),
('ManStPete', 'Manheim St Pete', true),
('ManTampa', 'Manheim Tampa', true),
('ManTexHobby', 'Manheim Texas Hobby', true),
('ManTulsa', 'Manheim Tulsa', true),
('MAR', 'MARQUIS COMPANIES', true),
('MarCountyJustice', 'Marshall County Justice Court', true),
('Marcus', 'Marcus Hart', true),
('Marquis', 'Marquiis Companies', true),
('MartinBryan', 'Martin, Byran Accounting and Consultling', true),
('Mascari', 'Mascari Glass Co.', true),
('MassMutual', 'Mass Mutual Insurance', true),
('Mav', 'Mav Transportatin LLC  / Luis Eduardo Aliva Vera', true),
('McCarty', 'McCarty Grandberry Engineering', true),
('MEER', 'MEER', true),
('Meineke', 'Meineke Car Care Center # 1853', true),
('Mel', 'Melkin Yanes', true),
('MemphisAutoParks', 'Memphis Auto Parts', true),
('MemphisImpound', 'City of Memphis', true),
('MickieWinn', 'Mickie Winn', true),
('MidAlloy', 'MidSouth Alloy Rim Repair / Stepehn M. Muruli', true),
('Midsouthattorney', 'Mid South Attorney Services LLC', true),
('MidsouthAutoGlass', 'MidSouth Auto Glass', true),
('MidSouthautoUph', 'Mid-South Auto Upholstery / Stephen L. Morelli', true),
('MidSouthEquipment', 'MidSouth Equipment Service', true),
('MiSSales', 'MidSouth Sales LLC', true),
('Mitchell', 'Mitchell', true),
('MLGW', 'MLGW', true),
('MMA', 'MT MORIAH AUTO SALES', true),
('MMarinDuenez', 'Maria G. Marin Duenez', true),
('MMartinez', 'Miguel Martinez / Martinez Auto Repair', true),
('MMurphy', 'Michael Murphy', true),
('MOates', 'Michael Oates', true),
('Monroe', 'Monroe County Justice Court', true),
('Montgomery Justice', 'Montgomery County Justice Court', true),
('Moonlighters', 'Moonlighters Enterprises Inc.', true),
('MooreDiag', 'Moore Diagnostics /  Johnny Martin', true),
('Motormate', 'Motormate LLC', true),
('MotorTrust', 'Motor Trust', true),
('MRagenhart', 'Mark Ragenhart', true),
('MrComplete', 'Mr Complete', true),
('MSDeptRev', 'MS Dept Revenue', true),
('MSEmploy', 'MS Dept Employment Security', true),
('MSFast', 'MS Fast Track Title Program', true),
('MSIndAuto', 'MS Independent Auto Deales Assn', true),
('MSMotorVeh', 'Motor Vehicle License Bureau', true)
ON CONFLICT (vendor_number) DO UPDATE SET
  vendor_name = EXCLUDED.vendor_name,
  updated_at = NOW();

-- Chunk 6 of 8
INSERT INTO vendors (vendor_number, vendor_name, is_active)
VALUES 
('MurElect', 'Murphree Walls Electric Company', true),
('Murray', 'MURRAY AUTO AUCTION INC.', true),
('MUSIC', 'MUSIC CITY  AUTO AUCTION OF NASHVILLE', true),
('MWhitting', 'Mike Whitting Enterprises', true),
('MWorks', 'Motor Works LLC', true),
('MyCentral', 'My Central Auction', true),
('Napa', 'Napa Auto Parts', true),
('NashMotors', 'Nashville Motors', true),
('Neo', 'Neo Finance Inc.', true),
('Nextday', 'Next Day Inc', true),
('NMSEPASN', 'Northcentral Electric Cooperative', true),
('NuWay', 'Nu-Way Auto Sales', true),
('O`Reilly', 'O`Reilly Auto Parts Inc.', true),
('OBAuto', 'OB Auto LLC', true),
('Office Depot', 'Office Depot', true),
('Oktibbeha', 'Oktibbeha County Justice Court', true),
('OneStop', 'One Stop Auto Repair & Body Shop Inc', true),
('Opus', 'Opus IVS, Inc.', true),
('Oseman', 'Oseman Insurance', true),
('PA', 'Phoenix Auto', true),
('PAA', 'Paucah Auto Auction Inc.', true),
('Paducah', 'Paducah Auto Auction', true),
('PaintMedix', 'Paint Medix, Inc.', true),
('Panola Justice', 'Panola County Justice Court', true),
('Passtime', 'Passtime', true),
('PayrollPaychex', 'Payroll Paychex', true),
('Pearl River', 'Pearl River County Justice Court', true),
('PeterHeist', 'Peter Heist', true),
('Pickwick Pro Shop', 'Pickwick Pro Shop', true),
('Platinum', 'Platinum Key Investigations', true),
('Pontotoc', 'Pontotoc County Justice Court', true),
('POOLE', 'ROBERT POOLE', true),
('PoplarCorner', 'Poplar Corner Exxon', true),
('Pops', 'Pop`s Towing & Recovery LC', true),
('Post Office', 'US Post Office', true),
('Powell', 'Powell Recovery', true),
('Powers', 'Michael Powers / Powers Automotive', true),
('PPS', 'Progressive Process Service', true),
('Premier', 'Premier Air Products LLC', true),
('PrentissJustice', 'Prentiss County Justice Court', true),
('PRIMA', 'PRIMALEND', true),
('PrimaFloor', 'Primalend Floor', true),
('PrimaInterest', 'Primalend Interest', true),
('Principle', 'Principle Toyota', true),
('ProgPrivate', 'Progressive Private Process', true),
('Progressive', 'Progressive Insurance', true),
('ProPaint', 'Pro Paint Repair LLC', true),
('Protrackers', 'Protection Trackers Inc.', true),
('Quality', 'Quality Glass Co. -   Kenneth A. Stanley  - A Quailty Glass', true),
('Quitman', 'Quitman County Justice Court', true),
('R&R', 'R&R Painting and Drywall', true),
('Raceway', 'Raceway Auto & Truck Parts', true),
('RaleighTire', 'Raleigh Tire', true),
('RankinJustCourt', 'Rankin County Justice Court', true),
('Rapid Recon', 'Rapid Recon Inc', true),
('RayMunns', 'Ray Munns', true),
('Rays', 'Ray`s Transport    /   Redha Marhoon', true),
('RDN', 'Recovery Database Network', true),
('Ready', 'Ready Logistics LLC    Manheim Remarketing Inc.', true),
('Regal', 'Regal Auto Credit Inc.', true),
('Republic', 'Republic Services', true),
('RFlyant', 'Ridge Flyant', true),
('Right2', 'Right Way Auto Transport Inc 2', true),
('Rightway', 'Right Way Auto Transport Inc', true),
('RimMedics', 'Rim Medics / Tyrone Johnson Sr.', true),
('Rios', 'Rios Auto Glass LLC', true),
('Rizo', 'Rizo Auto Transport Inc', true),
('RJohnson', 'Richard L. Johnson', true),
('RL rental', 'RL - Rental Properties', true),
('RLC', 'ROCK LEDGE CAPITAL', true),
('RLO', 'RLI Surety', true),
('Roadana', 'Roadana LLC', true),
('Roadrunner', 'Roadrunner Services LLC', true),
('Robert Chand', 'Robert Chandler II', true),
('Rockledge', 'Aaron Sledd / Rockledge Captial Mgt', true),
('Rogers', 'Rogers Seat Covers Co / Castillo, Aroldo', true),
('Rotation', 'Rotation Inc.', true),
('Route1', 'Route 1   / Shvon Noaman', true),
('ROYAL', 'ROYAL NISSAN', true),
('RPM', 'RPM Auto Group Inc', true),
('S&C', 'S & C Detail LLC', true),
('S&S', 'S & S Tire Wholesale', true),
('Sacharin', 'Sacharin, Kirkscey & Flexsenhar, Attorneys', true),
('Safeguard', 'Safeguard Business Systems Inc', true),
('SafetyKleen', 'Safety-Kleen Systems Inc.', true),
('Safeway', 'Safeway Trading & Services LLC', true),
('SAHill', 'Sarah A. Hill', true),
('Sam Ward', 'Jeffrey S. Ward II', true),
('Sandys', 'Sandy`s Auto Repair', true),
('SAR', 'Southern Automotive Remarketing LLC', true),
('SarahHill', 'Sarah Hill', true),
('Save', 'Save Equipment', true),
('Sayle', 'Sayle Oil Co.', true),
('SBouchie', 'Schelly Bouchie', true),
('SDennison', 'Samuel Dennison', true),
('Security', 'Security Fire Protection Company', true),
('SGS', 'Susan G. Sledd / SGS Capital .', true),
('SGS Capital', 'Susan G. Sledd / SGS Capital', true),
('Shedesoto', 'Sherriff of Desoto County', true),
('ShelbyCC', 'Shelby County Clerk Title Dept', true)
ON CONFLICT (vendor_number) DO UPDATE SET
  vendor_name = EXCLUDED.vendor_name,
  updated_at = NOW();

-- Chunk 7 of 8
INSERT INTO vendors (vendor_number, vendor_name, is_active)
VALUES 
('Shelbygeneral', 'Shelby County General Sessions Court Clerk', true),
('ShelbySherriff', 'Shelby County Sherriff Office', true),
('SheMars', 'Sherriff of Marshall County', true),
('SheTunica', 'Sherriff of Tunica County', true),
('Sigma', 'Sigma', true),
('Silverstar', 'Caroyln Parrish   DBA Silver Star Logistics', true),
('SimmBank', 'Simmons Bank', true),
('Simmons', 'Simmons and Son`s Logistics', true),
('SJoiner', 'Stephen D. Joiner', true),
('Skipbusters', 'Skipbusters', true),
('SKW', 'SKW Tow & Transport LLC', true),
('Snapon', 'Snap On Tools', true),
('SourPatch', 'Sour Patch Transportation Inv', true),
('Southern', 'Southern Tire & Wheel       JMP Enterprises Inc.', true),
('Southside Towing', 'Southside Towing & Recovery', true),
('Sportmans', 'Sportman`s Boat Storage Inc.', true),
('SRamey', 'James Steve Ramey Jr.', true),
('Standard', 'Standard Construction', true),
('STAR', 'DAVID', true),
('StateAR', 'State of Arkansas', true),
('StateFarm', 'State Farm Insurance', true),
('StateMS', 'State of MS', true),
('StateTN', 'State of TN', true),
('Stealth', 'Stealth Recovery Inc.', true),
('StephenDennison', 'Stephen Dennison Repair Services / Stephen Dennison', true),
('SteveRamey', 'James S. Ramey Jr.', true),
('Stewart', 'SDS Enterprices LLC - dba Stewart Detective Services', true),
('StoneCounty', 'Stone County Justice Court', true),
('Stonehiggs', 'Stone Higgs & Drexler', true),
('STravis', 'Stephen E. Travis', true),
('Stream', 'Stream', true),
('Sunflower', 'Sunflower County Justice Court', true),
('Sunrise', 'Sunrise Chevy Buick GMC', true),
('Tac', 'Tac Logistics Services LLC / Tochukwu Anyiam', true),
('Tallahatchie', 'Tallahatchie County Justice Court', true),
('TateJustCrt', 'Tate County Justice Court', true),
('TatesCustomsHauls', 'Tate`s Custome Hauls LLC / Robert Aaron Tate', true),
('Taurus', 'Taurus Transportation LLC', true),
('TaxesPaychex', 'Taxes Paychex', true),
('Taylor', 'Taylor Transportation LLC     Joshua I. Taylor', true),
('TC Towing', 'TC Towing & Recovery / Timothy Clark Jr.', true),
('TCalloway', 'Tramaine Calloway', true),
('Techno Lock Keys', 'Techno Lock Keys', true),
('Thomas', 'Thomas Trucking Inc.', true),
('THORO', 'THOROUGHBRED CAPITAL PARTNERS', true),
('Tippah', 'Tippah County Justice Court', true),
('TitleMax', 'Title Max', true),
('TLO', 'TransUnion', true),
('TNDeptRev', 'TN Dept Revenue', true),
('TNSecState', 'TN Secreaty of State', true),
('TopFlight', 'Top Flight Transport', true),
('Toyota', 'Toyota Financial Services', true),
('Traction', 'Traction Financial', true),
('Transtar', 'Transtar Industries LLC', true),
('Travelers', 'Travelers Insurance', true),
('Tri', 'AESOP Auto Parts, LLC', true),
('Triple R', 'Triple R', true),
('TriState Towing', 'Tri-State Towing & Recovery, LLC', true),
('True Accord', 'True Accord', true),
('Trus', 'True Reversals', true),
('Tunica Justice', 'Tunica County Justice Court', true),
('Twins', 'Twins Towing LLC', true),
('TXLAA', 'TEXAS LONE STAR AUTO AUCTION', true),
('Tyrone', 'Tyrone Delivery Services', true),
('UAR', 'United Auto Recovery Direct LLC', true),
('UHS', 'UHS Hardware', true),
('Unifirst', 'Unifirst Corp', true),
('Union', 'Union County Justice Court', true),
('UnionAuto', 'Union Auto Parts', true),
('UpandGone', 'Up & Gone Recovery', true),
('VAuto', 'VAuto', true),
('VehicleManagement', 'Vehicle Management Solutions', true),
('Venmo', 'Venmo', true),
('VIC', 'VICTORY AUTO SALES', true),
('Vintel', 'Vintel by Vinlogx', true),
('Volkswagon', 'Gossett Volkswagon', true),
('Volvo', 'Volvo Cars of Memphis', true),
('Warford', 'Warford Auto Parts', true),
('WarrenJustice', 'Warren County Justice Court', true),
('Washington', 'Washington County Justice Court', true),
('Waste', 'Waste Connections of TN', true),
('Wastebox', 'Wastebox', true),
('WasteMgt', 'Waste Mgt Corp Services, Inc', true),
('Wayne Justice', 'Wayne County Justice Court', true),
('Waynes', 'Wayne`s Auto Repair & Towing LLC', true),
('Weasels', 'Weasel`s Pawn Shop', true),
('Weco', 'Weco, Inc.', true),
('WellDone', 'Well Done Cleaning', true),
('Westlake', 'Westlake Financial', true),
('Whaley', 'Whaley`s Towing', true),
('Williams', 'Williams Equipment & Supply', true),
('Williamson', 'Williamson County Sherrif Office', true),
('Wittworks', 'Witt Works Environmental LLC', true),
('WJackson', 'Willie Jackson', true),
('WML', 'WML AUTO LLC', true),
('Wolfchase Toyota', 'Wolfchase Toyota', true),
('WolfchaseHyundai', 'Wolfchase Hyundai', true),
('Wolfes', 'Wolfe`s Evansville Auto Auction', true),
('WREG', 'WREG Memphis', true),
('Wynne Exhaust', 'Wynne Exhaust Distributors', true)
ON CONFLICT (vendor_number) DO UPDATE SET
  vendor_name = EXCLUDED.vendor_name,
  updated_at = NOW();

-- Chunk 8 of 8
INSERT INTO vendors (vendor_number, vendor_name, is_active)
VALUES 
('Yalobusha Justice', 'Yalobusha County Justice Court', true),
('Yazoo Justice Court', 'Yazoo County Justice Court', true),
('ZBrothers', 'Z Brothers Expedited, LLC', true),
('AdesaKnoxville', 'Adesa Knoxville', true),
('AllStarChevy', 'All Star Chevy', true),
('AmeriKansasCity', 'America`s Auto Auction Kansas City', true),
('AmerStLouis', 'America`s Auto Auction St Louis', true),
('Amy Doolin', 'Amy Doolin', true),
('CarMaxBoyntonBeach', 'Car Max Boynton Beach', true),
('CarMaxClearwater', 'Car Max Clearwater', true),
('CarMaxClermont', 'Car Max Clermont', true),
('CarMaxColoradoSprings', 'Car Max Colorado Springs', true),
('CarMaxColumbus', 'Car Max Columbus', true),
('CarMaxDallas', 'Car Max Dallas', true),
('CarMaxFtMyers', 'Car Max Ft Myers', true),
('CarMaxHickory', 'Car Max Hickory', true),
('CarMaxHouston', 'Car Max Houston', true),
('CarMaxIndianapolis', 'Car Max Indianapolis', true),
('CarMaxKansasCity', 'Car Max Kansas City', true),
('CarMaxLaurel', 'Car Max Laurel', true),
('CarMaxOklahomaCity', 'Car Max Oklahoma City', true),
('CarMaxRosedale', 'Car Max Rosedale', true),
('CarMaxTampa', 'Car Max Tampa', true),
('CarMaxWestColumbia', 'Car Max West Columbia', true),
('Great Choice', 'Great Choice Investment Inc.', true),
('Homer Skelton', 'Homer Skelton', true),
('IFR', 'I Finance Retail', true),
('InvoicePayroll', 'Invoice Payroll', true),
('JacieTransport', 'Jackie Transportation LLC', true),
('JimKerasSuraru', 'Jim Keras Subaru', true),
('KBishop', 'Keith Bishop', true),
('Kirk Brothers', 'Kirk Brothers of Batesville', true),
('ManBaltimoreWashington', 'Manheim Baltimore-Washingto', true),
('ManCleveland', 'Manheim Cleveland', true),
('ManDallas', 'Manheim Dallas', true),
('ManKansasCity', 'Manheim Kansas City', true),
('ManNashville', 'Manheim Nashville', true),
('ManPalmBeach', 'Manheim Palm Beach', true),
('ManSanAntonio', 'Manheim San Antonio', true),
('ManStatesville', 'Manheim Statesville', true),
('ManTulse', 'Manheim Tulsa', true),
('MHenryMotors', 'Morgan Henry Motors', true),
('MidSouthAutoUph', 'Mid-South Auto Upholstery / Stephen L. Morelli', true),
('MooreBrothers', 'Moore Brothers', true),
('MTodd', 'Michael Tom', true),
('Openlane', 'Openlane', true),
('Orlando', 'Orlando Longwood Auto Auction', true),
('Payroll', 'Payroll', true),
('Quality Auto Sales', 'Quality Auto Sales STL, LLC', true),
('Reed', 'Reed Transport LLC', true),
('SouthavenHonda', 'Southaven  Honda', true),
('TaxesPayroll', 'Taxes Payroll', true),
('Thoroughbred AA Clar', 'Thoroughbred AA of Clarksville', true),
('Vetway', 'Vetway Transporations Co. LLC', true)
ON CONFLICT (vendor_number) DO UPDATE SET
  vendor_name = EXCLUDED.vendor_name,
  updated_at = NOW();
